import Head from 'next/head';
import Home from '../components/home/Home';
// import Image from 'next/image';

export default function App() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}
