import Head from 'next/head';
import About from '../components/about/About';
import Home from '../components/home/Home';
import client from '../lib/sanity';

import { BsGithub, BsTwitter } from 'react-icons/bs';
import { FaLinkedinIn, FaReact } from 'react-icons/fa';
import { GrInstagram } from 'react-icons/gr';
import { FaHome, FaInfoCircle } from 'react-icons/fa';
import { IoMdConstruct } from 'react-icons/io';
import { MdContactPhone } from 'react-icons/md';
import { GiAmericanFootballHelmet } from 'react-icons/gi';
import { SiRedux, SiTailwindcss } from 'react-icons/si';
import Socials from '../components/showcase/Socials';
import Header from '../components/header/Header';
import Projects from '../components/projects/Projects';
import Skills from '../components/skills/Skills';
import Contacts from '../components/contacts/Contacts';
// import Socials from './Socials';
// import { sanityClient, urlFor } from '../lib/sanity';
// import Image from 'next/image';

export default function App({ abouts, projects, skills, experiences }) {
  return (
    <div className="bg-body">
      <Head>
        <title>Habeeb Ahmadu | Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Home />
      <About data={abouts} />
      <Projects data={projects} />
      <Skills skills={skills} experiences={experiences} />
      <Contacts />

      
    </div>
  );
}

export const getStaticProps = async () => {
  const aboutsData = `*[_type == 'abouts']`;
  const abouts = await client.fetch(aboutsData);

  const projectsData = `*[_type == 'works']`;
  const projects = await client.fetch(projectsData);

  const skillsData = `*[_type == 'skills']`;
  const skills = await client.fetch(skillsData);

  const experiencesData = `*[_type == 'workExperience']`;
  const experiences = await client.fetch(experiencesData);

  return {
    props: {
      abouts,
      projects,
      skills,
      experiences,
    },
  };
};
