import Head from 'next/head';
import About from '../components/about/About';
import Home from '../components/home/Home';

import { BsGithub, BsTwitter } from 'react-icons/bs';
import { FaLinkedinIn, FaReact } from 'react-icons/fa';
import { GrInstagram } from 'react-icons/gr';
import { FaHome, FaInfoCircle } from 'react-icons/fa';
import { IoMdConstruct } from 'react-icons/io';
import { MdContactPhone } from 'react-icons/md';
import { GiAmericanFootballHelmet } from 'react-icons/gi';
import { SiRedux, SiTailwindcss } from 'react-icons/si';
import Socials from '../components/showcase/Socials';
import Header from '../components/header/Header';
// import Socials from './Socials';
// import { sanityClient, urlFor } from '../lib/sanity';
// import Image from 'next/image';

export default function App() {
  return (
    <div className="">
      <Head>
        <title>Habeeb Ahmadu | Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <Home />
      <About />

      <div className="hidden md:block absolute bottom-8 left-8">
        <Socials path="#" Icon={BsGithub} />
        <Socials path="#" Icon={FaLinkedinIn} />
        <Socials path="#" Icon={GrInstagram} />
        <Socials path="#" Icon={BsTwitter} />
      </div>

      <div className="hidden md:block absolute top-60 right-8 ">
        <FaHome className="text-xl md:text-2xl lg:text-3xl text-gray-300 hover:text-btn font-bold mt-3" />
        <FaInfoCircle className="text-xl md:text-2xl lg:text-3xl text-gray-300 hover:text-btn font-bold mt-3" />
        <GiAmericanFootballHelmet className="text-xl md:text-2xl lg:text-3xl text-gray-300 hover:text-btn font-bold mt-3" />
        <IoMdConstruct className="text-xl md:text-2xl lg:text-3xl text-gray-300 hover:text-btn font-bold mt-3" />
        <MdContactPhone className="text-xl md:text-2xl lg:text-3xl text-gray-300 hover:text-btn font-bold mt-3" />
      </div>
    </div>
  );
}

// export const getStaticProps = async () => {
//   return {
//     props: {},
//   };
// };
